config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  get "/auth/signout", to: "authentication#signout"
  get "/auth/github/callback", to: "authentication#github"
  get "/auth/heroku/callback", to: "authentication#heroku"
  get "/auth/failure", to: "authentication#failure"

  resources :boards, only: [:create, :index, :show, :update] do
    match :toggle_subscription, on: :member, via: [:patch, :put]

    resources :applinks, only: [:index, :create]

    resources :cards, only: [:create, :show, :update] do
      match :move, on: :member, via: [:patch, :put]
      match :archive, on: :member, via: [:patch, :put]
      match :shipit, on: :member, via: [:patch, :put]
    end
  end

  resources :cards, only: [] do
    resources :comments, only: [:create, :update]
    resources :previews, only: :create
  end


  root to: "welcome#index"

  # Forwarding
  post "/forward/store_redirect", to: "forward#store_redirect"
  get "/forward", to: "forward#redirect"
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  skip_before_action :authenticate
  skip_before_action :require_invitation

  def index
    beta_user! if invitation_codes.include?(params[:invitation_code])
  end
end

app/views/welcome/index.html.erb
<header class="welcome-header clearfix">
  <img class="image catchup-logo" src="https://cdn.rawgit.com/catchup/catchup-web-assets/6fb5f5c68cfb11e5eb29169de6a5f26d1950b839/logo.svg">
  <h1 class="slogan">Simple flow meets rich feedback.</h1>
  <a class="signin-link" href="/auth/github">Sign in here if you are already a user</a>
</header>

<section class="signup-section clearfix">
  <h1 class="signup-title">Would you like to give it a try?</h1>
  <a class="signup-button" target="_blank" href="/auth/github">Sign up with GitHub</a>
  <p class="signup-text">We're letting you in, although you should note that Catchup is in early stages.<br>We use it every day ourselves and <a href="mailto:info@catchup.io">we would like to hear</a> anything you would like to say about the service.</p>
</section>

<section class="tutorial clearfix">
  <h1 class="tutorial-title">All you have to know is below in 7 quick steps:</h1>
  <div class="tutorial-step clearfix">
    <h2 class="video-title">1. Sign up with GitHub</h2>
    <div class="tutorial-video-bg clearfix">
      <img class="tutorial-video" src="https://cdn.rawgit.com/catchup/catchup-web-assets/ce7b553ddbbf3481838e334956806699d3eccd81/tutorial-1.gif">
    </div>
  </div>
  <div class="tutorial-step clearfix">
    <h2 class="video-title">2. Create a Catchup board for one of your repositories</h2>
    <div class="tutorial-video-bg clearfix">
      <img class="tutorial-video" src="https://cdn.rawgit.com/catchup/catchup-web-assets/ce7b553ddbbf3481838e334956806699d3eccd81/tutorial-2.gif">
    </div>
  </div>
  <div class="tutorial-step clearfix">
    <h2 class="video-title">3. Link to your Heroku app</h2>
    <div class="tutorial-video-bg clearfix">
      <img class="tutorial-video" src="https://cdn.rawgit.com/catchup/catchup-web-assets/ce7b553ddbbf3481838e334956806699d3eccd81/tutorial-3.gif">
    </div>
  </div>
  <div class="tutorial-step clearfix">
    <h2 class="video-title">4. Add to-dos using Markdown, prioritize with drag & drop</h2>
    <div class="tutorial-video-bg clearfix">
      <img class="tutorial-video" src="https://cdn.rawgit.com/catchup/catchup-web-assets/ce7b553ddbbf3481838e334956806699d3eccd81/tutorial-4.gif">
    </div>
  </div>
  <div class="tutorial-step clearfix">
    <h2 class="video-title">5. Work with unique branches and create pull requests on GitHub</h2>
    <div class="tutorial-video-bg clearfix">
      <img class="tutorial-video" src="https://cdn.rawgit.com/catchup/catchup-web-assets/ce7b553ddbbf3481838e334956806699d3eccd81/tutorial-5.gif">
    </div>
  </div>
  <div class="tutorial-step clearfix">
    <h2 class="video-title">6. Review and share production-like apps on Heroku for each branch</h2>
    <div class="tutorial-video-bg clearfix">
      <img class="tutorial-video" src="https://cdn.rawgit.com/catchup/catchup-web-assets/ce7b553ddbbf3481838e334956806699d3eccd81/tutorial-6.gif">
    </div>
  </div>
  <div class="tutorial-step clearfix">
    <h2 class="video-title">7. Ship features fast with a single click!</h2>
    <div class="tutorial-video-bg clearfix">
      <img class="tutorial-video" src="https://cdn.rawgit.com/catchup/catchup-web-assets/b913b3ae51adba167c27ae7c68d8f3229cb20f5e/tutorial-7.gif">
    </div>
  </div>
</section>

<section class="signup-section clearfix">
  <h1 class="signup-title">Ready to give it a try?</h1>
  <a class="signup-button" target="_blank" href="/auth/github">Sign up with GitHub</a>
  <p class="signup-text">We're letting you in, although you should note that Catchup is in early stages.<br>We use it every day ourselves and <a href="mailto:info@catchup.io">we would like to hear</a> anything you would like to say about the service.</p>
</section>

<section class="newsletter-section clearfix">
  <h1 class="newsletter-title">Would you like to know about new features?</h1>
  <a class="subscribe-button" target="_blank" href="http://eepurl.com/buvLmT">Subscribe to newsletter</a>
  <p class="newsletter-text">We will e-mail you only we have something really interesting to share.<br>We promise you won't get any spam from us, ever!</p>
</section>

<%= render "will_redirect_to", redirect_url: auth_github_callback_url %>