config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  get "/auth/signout", to: "authentication#signout"
  get "/auth/github/callback", to: "authentication#github"
  get "/auth/heroku/callback", to: "authentication#heroku"
  get "/auth/failure", to: "authentication#failure"

  resources :boards, only: [:create, :index, :show, :update] do
    match :toggle_subscription, on: :member, via: [:patch, :put]

    resources :applinks, only: [:index, :create]

    resources :cards, only: [:create, :show, :update] do
      match :move, on: :member, via: [:patch, :put]
      match :archive, on: :member, via: [:patch, :put]
      match :shipit, on: :member, via: [:patch, :put]
    end
  end

  resources :cards, only: [] do
    resources :comments, only: [:create, :update]
    resources :previews, only: :create
  end


  root to: "welcome#index"

  # Forwarding
  post "/forward/store_redirect", to: "forward#store_redirect"
  get "/forward", to: "forward#redirect"
end

app/controllers/applinks_controller.rb
class ApplinksController < ApplicationController
  def index
    board_id = params[:board_id]

    @api_key = params[:api_key]
    @heroku_apps = Heroku::Application.all(@api_key)
    @board = Board.find(board_id)
  end

  def create
    board = Board.find(params[:board_id])

    board.update_attributes(
      app_name: params[:app_name], heroku_api_key: params[:api_key]
    )

    redirect_to board
  end
end

app/views/applinks/_heroku_form.html.erb
<div class="applinks-_heroku_form clearfix">

<article class="app-link clearfix">
  <header class="heroku-app-header clearfix">
    <h3 class="heroku-app-title"><%= app.name %></h3>
  </header>

  <%= form_tag({ url: board_applinks_url(board) }, class: "heroku-app-form clearfix") do %>
    <%= hidden_field_tag :app_name, app.name %>
    <%= hidden_field_tag :api_key, api_key %>
    <%= submit_tag "Link to board", class: "submit" %>
  <% end %>
</article>

</div>

app/views/applinks/index.html.erb
<section class="applinks-section clearfix">
  <h2 class="section-title">Below is list of all Heroku apps available to you. Select one to link it to board so you can create review apps and ship!</h2>
  <div class="heroku-apps-container clearfix">
    <%= render partial: "heroku_form",
               collection: @heroku_apps, as: :app,
               spacer_template: "separator",
               locals: { board: @board, api_key: @api_key } %>
  </div>
</section>