config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  get "/auth/signout", to: "authentication#signout"
  get "/auth/github/callback", to: "authentication#github"
  get "/auth/heroku/callback", to: "authentication#heroku"
  get "/auth/failure", to: "authentication#failure"

  resources :boards, only: [:create, :index, :show, :update] do
    match :toggle_subscription, on: :member, via: [:patch, :put]

    resources :applinks, only: [:index, :create]

    resources :cards, only: [:create, :show, :update] do
      match :move, on: :member, via: [:patch, :put]
      match :archive, on: :member, via: [:patch, :put]
      match :shipit, on: :member, via: [:patch, :put]
    end
  end

  resources :cards, only: [] do
    resources :comments, only: [:create, :update]
    resources :previews, only: :create
  end


  root to: "welcome#index"

  # Forwarding
  post "/forward/store_redirect", to: "forward#store_redirect"
  get "/forward", to: "forward#redirect"
end

app/models/card.rb
class Card < ActiveRecord::Base
  after_create :assign_branch_name

  include RankedModel

  scope :unarchived, -> { where(archived: false) }

  has_many :comments, -> { order(created_at: :desc) }
  belongs_to :list
  delegate :board, to: :list

  ranks :position, with_same: :list_id, scope: :unarchived

  validates :title, presence: true

  def move_to(list_id: nil, position:)
    changed_list! if Integer(list_id) != self.list_id

    update_attribute(:list_id, list_id) if list_id
    update_attribute(:position_position, position)
  end

  def changed_list?
    @changed_list == true
  end

  def changed_list!
    @changed_list = true
  end

  def post_comment(by:, with:)
    attributes = with.merge(user: by)
    comments.create(attributes)
  end

  def archive
    update_attribute(:archived, true)
  end

  def involved_users
    board.subscribers
  end

  def previewing!
    update_attribute(:previewing, true)
  end

  def previewed!(url)
    update_attributes(previewing: false, preview_url: url)
  end

  def previewed?
    !previewing? && preview_url?
  end

  def branch_tarball
    uri = build_repository_uri
    uri.path += "archive/#{branch_name}.tar.gz"
    uri.to_s
  end

  def compare_url(card_url)
    pr_body = ""
    pr_body += "#{description}\n\n" if description.present?
    pr_body += "--\n[Open card on Catchup](#{card_url})"

    uri = build_repository_uri
    uri.path += "compare/#{branch_name}"
    uri.query = "expand=1&title=#{CGI.escape(title)}&body=#{CGI.escape(pr_body)}"
    uri.to_s
  end

  private

  WORDS_BLACKLIST = ["after", "although", "and", "as", "because", "before", "but", "even", "for", "if", "in", "nor", "only", "of", "or", "since", "so", "than", "that", "then", "though", "till", "unless", "until", "when", "whenever", "where", "whereas", "wherever", "while", "yet"]

  def assign_branch_name
    words = title.downcase.gsub(/[[:punct:]]/, "").split
    words -= WORDS_BLACKLIST
    slug = words.take(5).join("-")

    self.branch_name = "catchup/#{id}-#{slug}"
    save!
  end

  def build_repository_uri
    uri = URI(board.repository_url)
    uri.path += "/" unless uri.path.ends_with?("/")
    uri
  end
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  def create
    @card = board.create_card(card_params)

    if @card.valid?
      card_html = render_to_string(@card, locals: { list_class: "todo" })
      CardObserver.publish(:card_created, @card, current_user, card_html)
    else
      flash[:alert] = I18n.t("cards.create.error")
    end

    redirect_to board
  end

  def show
    @card = board.cards.find(params[:id])
  end

  def move
    @card = board.cards.find(params[:id])
    @card.move_to(move_params)

    CardObserver.publish(:card_moved, @card, current_user, move_params)

    render nothing: true
  end

  def archive
    @card = board.cards.find(params[:id])
    @card.archive

    CardObserver.publish(:card_archived, @card, current_user)

    redirect_to [@card.board, @card]
  end

  def shipit
    @card = board.cards.find(params[:id])

    base_branch = current_user.github.repo(board.title).default_branch
    head_branch = @card.branch_name

    current_user.github.merge(@card.board.title, base_branch, head_branch)
    current_user.github.delete_branch(@card.board.title, head_branch)

    @card.archive
    CardObserver.publish(:card_archived, @card, current_user)

    flash[:success] = t("cards.shipit.success", card: @card.title)
    redirect_to @card.board
  rescue Octokit::Conflict
    flash[:error] = t("cards.shipit.merge-conflict", branch: head_branch)

    redirect_to [@card.board, @card]
  rescue Octokit::NotFound
    flash[:error] = t("cards.shipit.not-found", branch: head_branch)

    redirect_to [@card.board, @card]
  end

  def update
    card = board.cards.find(params[:id])
    card.update_attributes(card_params)

    redirect_to [card.board, card]
  end

  private

  def board
    @board ||= Board.find(params[:board_id])
  end

  def card_params
    params.require(:card).permit(:title, :description)
  end

  def move_params
    params.require(:card).permit(:list_id, :position).symbolize_keys
  end
end

app/views/cards/_archive.html.erb
<%= form_for [:archive, card.board, card], html: { class: 'archive-card-form clearfix' } do |f| %>
  <button class="archive-card"><%= t('.submit') %></button>
<% end %>

app/views/cards/_card.html.erb
<div class="cards-_card clearfix">

<a class="card-wrapper clearfix"
   href="<%= url_for([card.board, card]) %>"
   data-role="card"
   data-card-id="<%= card.id %>">

  <div class="card-title-container clearfix">
    <p class="<%= list_class %>-card-title"><%= card.title %></p>
  </div>

  <%= form_for [:move, card.board, card], remote: true, data: { role: "card-update-form" } do |f| %>
    <%= f.hidden_field :list_id %>
    <%= f.hidden_field :position %>
  <% end %>
</a>

</div>

app/views/cards/_form.html.erb
<div class="cards-_form clearfix">

<%= form_for [board, card], html: { class: 'card-form clearfix' } do |f| %>
  <button class="cancel-create-card" type="button" data-ux-cancel-create-card>close</button>
  <%= f.text_field :title, class: "card-title",
                    placeholder: t(".title-placeholder") %>
  <%= f.text_area :description, class: "card-description",
                   placeholder: t(".description-placeholder") %>
  <%= button_tag t(".submit"), class: 'create-card' %>
<% end %>

</div>

app/views/cards/_inline_form.html.erb
<div class="cards-_inline_form clearfix">

<%= form_for [card.board, card], html: { class: "edit-card-form clearfix" } do |f| %>
  <button class="cancel-update-card" type="button" data-ux-cancel-update-card>close</button>
  <%= f.text_field :title, placeholder: "Title",
                    class: "card-title" %>
  <%= f.text_area :description, placeholder: "Markdown friendly description",
                   class:"card-description"  %>
  <button class="update-card" type="submit">Save changes</button>
<% end %>

</div>

app/views/cards/_review_app.html.erb
<section class="review-app clearfix">

  <h1 class="review-app-label"><%= t('.label') %></h1>
  <a class="open-view-app desktop"
     target="_blank" href="<%= card.preview_url %>">
     <%= card.preview_url %>
   </a>
  <button class="copy-view-app-link"
          data-clipboard-text='<%= card.preview_url %>'>
          <%= t('.copy') %>
  </button>

  <a class="open-review-app mobile"
     target="_blank" href="<%= card.preview_url %>"><%= t('.open_mobile') %></a>

</section>

app/views/cards/_review_app_ready.html.erb
<section class="review-app-section clearfix">

  <h1 class="review-app-label"><%= t('.label') %></h1>
  <a class="open-view-app desktop"
     target="_blank" href="<%= card.preview_url %>">
     <%= card.preview_url %>
   </a>
  <button class="copy-view-app-link"
          data-clipboard-text='<%= card.preview_url %>'>
          <%= t('.copy') %>
  </button>

  <a class="open-review-app mobile"
     target="_blank" href="<%= card.preview_url %>"><%= t('.open_mobile') %></a>

</section>

app/views/cards/_review_app_waiting.html.erb
<section class="waiting-review-app-section clearfix">
  <p class="waiting-review-app-message"><%= t('.message') %></p>
</section>

app/views/cards/_shipit.html.erb
<%= form_for [:shipit, card.board, card], html: { class: 'shipit-form clearfix' } do |f| %>
  <%= button_tag t(".submit"), class: 'shipit' %>
<% end %>

app/views/cards/_waiting_review_app.html.erb
<div class="wait-review-app clearfix">
  <p class="wait-review-app-message"><%= t('.message') %></p>
</div>

app/views/cards/show.html.erb
<%= content_for :main_action do %>
  <% unless @card.archived? %>
  <%= render "header_actions/create_review", card: @card %>
  <% end %>
<% end %>

<div data-role="single-card" data-board-id="<%= @card.board.id %>">

<% unless @card.archived? %>
  <% if @card.previewing? %>
    <%= render "review_app_waiting" %>
  <% elsif @card.previewed? %>
    <%= render "review_app_ready", card: @card %>
  <% end %>
<% end %>

<section class="edit-card-section clearfix" data-ux-edit-card-section>
  <%= render "cards/inline_form", card: @card %>
</section>

<section class="card-header-section clearfix" data-ux-card-header-section>
  <div class="card-info clearfix">
    <a class="go-back-to-board" href="<%= board_path @card.board %>">
      <%= t('accessibility.go-back-to-board') %>
    </a>
    <h1 class="card-title"><%= @card.title %></h1>
    <div class="card-description-container clearfix">
      <%= render "markdown", text: @card.description %>
    </div>
  </div>
  <div class="card-actions clearfix">
    <%= render "cards/shipit", card: @card %>
    <button class="copy-branch-name"
            data-clipboard-text='<%= @card.branch_name %>'>
            <%= t('.copy-branch') %>
    </button>
    <a class="open-pr-on-github"
       target="_blank" href="<%= @card.compare_url(url_for([@card.board, @card, only_path: false])) %>">
       <%= t('.open-pr-on-github') %>
     </a>
    <a class="edit-card" href="#" data-ux-edit-card><%= t('.edit') %></a>
    <%= render "cards/archive", card: @card %>
  </div>
</section>
<div class="comments-wrapper clearfix">
  <div class="comment-form-container clearfix" data-ux-comment-form-container>
    <%= render "comments/form", comment: Comment.new, card: @card %>
  </div>
  <div class="comments-container clearfix">
    <%= render @card.comments %>
  </div>
</div>

</div>