config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  get "/auth/signout", to: "authentication#signout"
  get "/auth/github/callback", to: "authentication#github"
  get "/auth/heroku/callback", to: "authentication#heroku"
  get "/auth/failure", to: "authentication#failure"

  resources :boards, only: [:create, :index, :show, :update] do
    match :toggle_subscription, on: :member, via: [:patch, :put]

    resources :applinks, only: [:index, :create]

    resources :cards, only: [:create, :show, :update] do
      match :move, on: :member, via: [:patch, :put]
      match :archive, on: :member, via: [:patch, :put]
      match :shipit, on: :member, via: [:patch, :put]
    end
  end

  resources :cards, only: [] do
    resources :comments, only: [:create, :update]
    resources :previews, only: :create
  end


  root to: "welcome#index"

  # Forwarding
  post "/forward/store_redirect", to: "forward#store_redirect"
  get "/forward", to: "forward#redirect"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  attr_reader :current_user
  helper_method :current_user, :signed_in?, :beta_user?

  before_action :authenticate
  before_action :require_invitation

  def signed_in?
    current_user != nil
  end

  def authenticate
    @current_user = User.find_by(id: session[:current_user])

    redirect_to root_url if current_user.nil?
  end

  def require_invitation
    return unless Rails.env.production?

    redirect_to root_url unless beta_user?
  end

  def beta_user?
    cookies[:beta_user].present?
  end

  def beta_user!
    cookies.permanent[:beta_user] = true
  end

  def invitation_codes
    ENV["INVITATION_CODES"].to_s.split(";").compact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def site_markdown(text)
    markdown = Redcarpet::Markdown.new(
      CatchupMarkdownRenderer,
      fenced_code_blocks: true,
      autolink: true,
      disable_indented_code_blocks: true,
      strikethrough: true,
      underline: true
    )

    markdown.render(emojify(text).to_s).html_safe
  end

  def email_markdown(text)
    markdown = Redcarpet::Markdown.new(
      Redcarpet::Render::HTML,
      fenced_code_blocks: true,
      autolink: true,
      disable_indented_code_blocks: true,
      strikethrough: true,
      underline: true
    )

    markdown.render(emojify(text).to_s).html_safe
  end

  def emojify(content)
    return if content.blank?

    content.gsub(/:([\w+-]+):/) do |match|
      if emoji = Emoji.find_by_alias($1)
        %(<img alt=":#$1:" src="#{image_url("emoji/#{emoji.image_filename}")}" style="vertical-align:middle; width: 20px; height: 20px" />)
      else
        match
      end
    end.html_safe
  end

  def flash_messages
    flash
      .to_hash
      .symbolize_keys
      .slice(:error, :alert, :notice, :success)
      .map { |name, msg| [name, Array(msg)] }
      .to_h
  end
end

app/views/application/_flashes.html.erb
<div class="application-_flashes clearfix">

<div class="flash-container clearfix">
  <div class="flash notice clearfix" data-ux-flash id="clipboard-notice">
    <p class="message"><%= t(".copied-to-clipboard") %></p>
  </div>

  <% flash_messages.each do |name, msgs| %>
    <% msgs.each do |msg| %>
    <div class="flash <%= name %> clearfix" data-ux-flash>
      <button class="dismiss" data-ux-flash-dismiss></button>
      <p class="message"><%= msg %></p>
    </div>
    <% end %>
  <% end %>
</div>

</div>

app/views/application/_footer.html.erb
<div class="application-_footer clearfix">

<footer class="site-footer clearfix">
  <p class="brought-by">Brought to you by</p>
  <div class="founders clearfix">
    <a class="founder-antonio clearfix"
       target="_blank" href="http://github.com/<%= User.antonio.nickname %>">
      <%= render Avatar.large(User.antonio) %>
    </a>
    <p class="and">&amp;</p>
    <a class="founder-ali clearfix"
       target="_blank" href="http://github.com/<%= User.ali.nickname %>">
      <%= render Avatar.large(User.ali) %>
    </a>
  </div>
  <p class="made-in">Made in</p>
  <div class="italian-flag clearfix">
    <div class="italian-flag-green"></div>
    <div class="italian-flag-white"></div>
    <div class="italian-flag-red"></div>
  </div>
</footer>

</div>

app/views/application/_header.html.erb
<div class="application-_header clearfix">

<header class="site-header clearfix" data-ux-header>
  <div class="user-profile clearfix">
    <div class="avatars-container clearfix">
      <%= render Avatar.small(current_user) %>
    </div>
  </div>
  <img class="catchup-icon" src="https://cdn.rawgit.com/catchup/catchup-web-assets/870b23673591525b89dc489f6e503d62bad6a952/icon.svg">
  <div class="main-action-container clearfix">
    <%= content_for :main_action %>
  </div>
</header>

</div>

app/views/application/_markdown.html.erb
<div class="markdown clearfix">

<%= site_markdown(text) %>

</div>

app/views/application/_navigation.html.erb
<header>
  <nav>
    <%= link_to t('see_boards'), boards_path %>
  </nav>
  <%= content_tag :h1, t('greeting', user: session[:current_user]) if signed_in? %>
</header>

app/views/application/_separator.html.erb
<hr>

app/views/application/_will_redirect_to.html.erb
<% unless Rails.env.test? %>
<script>
$.post(
  "<%= Forwarder::URLHelpers.store_redirect_url %>",
  { redirect_url: "<%= redirect_url %>" }
)
</script>
<% end %>